spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account_identity?characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: acc-id-service
    password: q1w2e3r4
    initialize: true
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: false
    test-on-borrow: true
    validation-query: SELECT 1

flyway:
  user: flyway
  password: q1w2e3r4
  datasource:
    url: ${spring.datasource.url}
    username: ${flyway.user}
    password: ${flyway.password}
    driver-class-name: ${spring.datasource.driver-class-name}
    initialize: false
    continue-on-error: false
    test-on-borrow: true
    validation-query: SELECT 1

escrow:
  encryption:
    password: Change-This-On-Production

ethereum:
  node:
    url: http://big-parity.euro2.ee:8545
  contract:
    master: "0xa10a263D4336E4466502b2889D27D04582a86663"
    approve: "0xA5f9b79Fc7f067Df25A795685493514A295A8A81"
    delegate: "0xaf71e622792f47119411ce019f4ca1b8d993496e"

wallet.server.url: http://wallet.euro2.ee:8080
ref.server.url: http://wallet.euro2.ee:8000/

---

spring:
    profiles: development
server:
    port: 9080
wallet.server.url: http://localhost:8080
